# Generated by Django 2.2.28 on 2024-11-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.IntegerField()),
                ('nombre_actuel', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id_creature', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('Affamé', 'Affamé'), ('Repus', 'Repus'), ('Actif', 'Actif'), ('Fatigué', 'Fatigué'), ('Endormi', 'Endormi')], max_length=20)),
                ('espece', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Equipement')),
            ],
        ),
    ]
